### PR TITLE
Add gui

### LINKED ISSUE #134: GUI application for discord to send message with tkinter
## Script Title - GUI application for discord to send messages with Tkinter

GUI will take 2 input. 
- bot name
- message

It will help to automate some task like greeting message and warning. you can also send message to the channel anonymously.

you need channel webhook_url for sending a message.

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by shrn2**
dcgui

Added the necessary GUI elements.

### CODE REVIEW

**Review by codeperfectplus — APPROVED** [review]
Thanks for improving the project.
but assign on the issue before making the change in the code. it helps us to track issue and Pr.
use flake8 for code linting

**Comment by shrn2** [comment]
@codePerfectPlus Done flake8 linting

**Comment by codeperfectplus** [comment]
Screenshot from 2020-10-03 13-59-26

Using Text instead of Entry can make it better, Actually, I was working on this GUI last night. Have some changes left

**Comment by codeperfectplus** [comment]
Making some change to the GUI.
@tre3x

**Pull request merged**
