### PR TITLE
Added Wifi Password Getter Script

### LINKED ISSUE #157: Stored Wifi Passwords Getter
## Script Title -Stored Wifi Passwords Getter

**what will change** -
The script will be able to get any stored wifi connections on your laptop/pc and print their names with passwords. Also, if it's an open connection then it would just print it's name.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by harshit-saraswat**
Solved Issue #157 

Tasks done:

- [x] Feature Added
- [x] Code Added
- [x] Readme.md Added

### CODE REVIEW

**Comment by harshit-saraswat** [comment]
@codePerfectPlus please review.

**Review by codeperfectplus — COMMENTED** [review]
I don't have much knowledge about subprocess module, I am getting an error while running your code.
FileNotFoundError: [Errno 2] No such file or directory: 'netsh': 'netsh'

Os - LinuxMint 19.3

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions

**Comment by harshit-saraswat** [comment]
> I don't have much knowledge about subprocess module, I am getting an error while running your code.
> FileNotFoundError: [Errno 2] No such file or directory: 'netsh': 'netsh'
> 
> Os - LinuxMint 19.3

I didn't try it for Linux, sorry about that.

**Comment by codeperfectplus** [comment]
I checked it's only for windows os. `ntesh` is windows os cmd command so it will not work on Linux or mac os.
In computing, netsh, or network shell, is a command-line utility included in Microsoft's Windows NT line of operating systems beginning with Windows 2000. It allows local or remote configuration of network devices such as the interface. -- `Wikipedia`

**Pull request merged**
