### PR TITLE
Encrypt PDF Final Commit

### PR DESCRIPTION
**Pull request by AmeyaJain-25**
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added README.md with my script

### Add your Script|Author_Name|ShortItroduction in Main README.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
We have added flake8 for clean code.

Run you python file with flake8 for clean code

**Comment by AmeyaJain-25** [comment]
Hi @codePerfectPlus ,
 I'm new to contribution.
What should i do know?
Is my code wrong?
I didn't understood.
Please help me out

**Comment by codeperfectplus** [comment]
Please can you recreate pull request?

**Comment by AmeyaJain-25** [comment]
Okay,
I'll recreate a PR.

**Pull request closed without merging**
