### PR TITLE
Feature/sorting visulaizer

### LINKED ISSUE #55: Sound Visualizer
## Script Title - sound_visualizer.py

**what will change** -

New script to visualize sound waves on the graph.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by debdutgoswami**
### What have you Changed -

Added script to  visualize various sorting algorithms

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added README.md with my script

### Add your Script|Author_Name|ShortItroduction in Main README.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
@debdutgoswami Please improve your code. It has some error. Click on details for eroor

**Comment by debdutgoswami** [comment]
@codePerfectPlus sure I'll fix those. Kindly reopen the PR so that I can push the changes

**Comment by debdutgoswami** [comment]
@codePerfectPlus the error is not in my code. It requires **ffmpeg** to be present in the system. This is the reason why GitHub action is failing.

**Comment by codeperfectplus** [comment]
```
./sorting_visualizer/sorting_visulaizer.py:1:1: F401 'matplotlib' imported but unused
./sorting_visualizer/sorting_visulaizer.py:1:18: E401 multiple imports on one line
./sorting_visualizer/sorting_visulaizer.py:10:19: F541 f-string is missing placeholders
./sorting_visualizer/sorting_visulaizer.py:11:22: F541 f-string is missing placeholders
./sorting_visualizer/sorting_visulaizer.py:12:22: F541 f-string is missing placeholders
```
You should install flake8 for lining code. it's mentioned in READE

**Comment by codeperfectplus** [comment]
@debdutgoswami you are importing libraries but not using them. F-string has some rules for use.

**Comment by debdutgoswami** [comment]
@codePerfectPlus got it. Will do it

**Comment by debdutgoswami** [comment]
@codePerfectPlus fixed

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions

**Pull request merged**
