### PR TITLE
email_sending_script

### LINKED ISSUE #3: Email sending script using smptlib | Python
## Script Title -Email sending script using smptlib

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed
- add your program name & Author name in the main readme

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by nishit130**
### What have you Changed -
Added the email sending script

### Issue no.-
resolves #3 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [x] One Change in one Pull Request
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added README.md with my script

### CODE REVIEW

**Review by codeperfectplus — APPROVED** [review]
Please add your script_name | Author_name  |Introduction as well next time

**Comment by nishit130** [comment]
@codePerfectPlus should I do it in the main README.md file or you will do it?

**Comment by codeperfectplus** [comment]
I did it

**Comment by nishit130** [comment]
@codePerfectPlus  ok there is a double entry in the README.md file just remove any one of them
 Thank You,

**Pull request merged**
