### PR TITLE
TelegramEchoBot & InstaGramBot

### LINKED ISSUE #369: TelegramEchoBot & InstaGramBot.
## Script Title -
 TelegramEchoBot & InstaGramBot.
**what will change** -

TelegramEchoBot
TelegramEchoBot is a simple python script which echo the messages got from the user on telegram without any Library and Framework

InstaGramBot
InstGramBot is a simple python script to automate Instagram activities, like unfollow every user, unfollow non-followers,...
fully cli.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by MQ-xz**
# added TelegramEchoBot & InstaGramBot.

## TelegramEchoBot 
 TelegramEchoBot is a simple python script which echo the messages got from the user on telegram without any Library and Framework

## InstaGramBot
 InstGramBot is a simple python script to automate Instagram activities, like unfollow every user, unfollow non-followers,...
fully cli.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
Please test your script and lint the errors.

**Comment by MQ-xz** [comment]
Lint errors fixed and Script Updated.

**Comment by Mr-Mishraji** [comment]
@Xpykerz what is lint error and how to solve it

**Comment by MQ-xz** [comment]
@Mr-Mishraji  linting is just used to make your code more syntactical and stylistic. here it's flake8. install flake8 and just run your code using flake8 filename.py it show the issues. like unwanted spaces or lines. just figure out. it's easy. for more info check [flake8 documentations.](https://flake8.pycqa.org/en/latest/)

**Comment by Mr-Mishraji** [comment]
@Xpykerz thank you

**Comment by codeperfectplus** [comment]
Please can you create an issue for the current script? creating an issue before changing code is the right way. It helps the team to avoid duplicate scripts and unassigned and spam Pull requests.

**Comment by MQ-xz** [comment]
DONE

**Comment by codeperfectplus** [comment]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
Happy Coding

**Pull request merged**
