### PR TITLE
Pomodoro timer gui

### PR DESCRIPTION
**Pull request by dyannya**
# Pull Request 
#### What have you Changed

Added a Simple Pomodoro timer class with an easy-to-navigate user interface.

### Issue no. #484 

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation and my code is well-linted with flake8.
- [x] I have added README.md and requirements.txt with my script

## acknowledgment
- [x] I have tested the script and distributed it under an MIT license.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
~@dyannya This issue was assigned to someone else. someone was working on that. let me confirm the status. if he/she is not working on that so I can merge the PR.~

**Comment by dyannya** [comment]
> @dyannya This issue was assigned to someone else. someone was working on that. let me confirm the status. if he/she is not working on that so I can merge the PR.

Hello! From what I could recall, I believe I was the one last assigned to issue #484.

**Comment by codeperfectplus** [comment]
My bad, There is a duplicate issue created by someone.

**Comment by codeperfectplus** [comment]
Please delete .idea and inspection folder which was created by Pycharm.

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions.

you can join us on telegram for more updates about Hacktoberfest.
Hacktoberfest Channel:- t.me/hacktober2022

Happy hacktoberfest

**Pull request merged**
