### PR TITLE
Python Script to convert Different International Currencies 

### LINKED ISSUE #189: Currency Converter Script in python..
## Script Title -

**This Script Uses access key of https://fixer.io to convert different currencies value.** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by vighneshdeepweb**
# Pull Request Template

**currency.py(Changes the currencies value via use of https://fixer.io embedded in Python) ** -

**What have you Changed** #191 

Want to add a new script so generated a PR for a new script

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation and my code is well lint with flake8.
- [x] I have added README.md and requirements.txt with my script

If the issue was not assigned to you Please don't make a PR. It will mark as invalid.

##OUTPUT
output1

Join Us on Discord:- https://discord.gg/JfbK3bS

### CODE REVIEW

**Comment by codeperfectplus** [comment]
please use flake8 for python code standards

**Comment by vighneshdeepweb** [comment]
OK but @codePerfectPlus I have never used flake8 before can u explain me what exactly the bot is checking which is continuously giving error and how can i resolve that pls sir...

**Comment by vighneshdeepweb** [comment]
sry for such a messy PR but was not able to do the flake8 linting so @codePerfectPlus sry

**Comment by vighneshdeepweb** [comment]
Sir now i have runned my script via use of flake8 now do i have to generate a PR once again??

**Comment by vighneshdeepweb** [comment]
Sir not able to pass the lint checker.Code is ready and is executing also but when i am trying for PR with flake8 linting then also it is not passing pls help sir @codePerfectPlus

**Comment by codeperfectplus** [comment]
```
./Arrange/arrange.py:1:10: E261 at least two spaces before inline comment
./Arrange/arrange.py:1:35: W291 trailing whitespace
./Arrange/arrange.py:3:14: E261 at least two spaces before inline comment
./Arrange/arrange.py:3:50: W291 trailing whitespace
./Arrange/arrange.py:5:32: W291 trailing whitespace
./Arrange/arrange.py:6:22: W291 trailing whitespace
./Arrange/arrange.py:7:18: W291 trailing whitespace
./Arrange/arrange.py:9:37: W291 trailing whitespace
./Arrange/arrange.py:11:1: E741 ambiguous variable name 'l'
./Arrange/arrange.py:11:54: W291 trailing whitespace
./Arrange/arrange.py:12:8: W291 trailing whitespace
./Arrange/arrange.py:14:41: W291 trailing whitespace
./Arrange/arrange.py:16:16: W291 trailing whitespace
./Arrange/arrange.py:17:1: W191 indentation contains tabs
./Arrange/arrange.py:17:25: W291 trailing whitespace
./Arrange/arrange.py:18:1: W191 indentation contains tabs
./Arrange/arrange.py:18:14: W291 trailing whitespace
./Arrange/arrange.py:19:13: W291 trailing whitespace
./Arrange/arrange.py:21:34: W291 trailing whitespace
./Arrange/arrange.py:22:34: W291 trailing whitespace
./Arrange/arrange.py:23:37: W291 trailing whitespace
./Arrange/arrange.py:25:26: W291 trailing whitespace
./Arrange/arrange.py:26:1: W191 indentation contains tabs
./Arrange/arrange.py:26:21: W291 trailing whitespace
./Arrange/arrange.py:27:1: W191 indentation contains tabs
./Arrange/arrange.py:27:23: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:27:25: W605 invalid escape sequence '\ '
./Arrange/arrange.py:27:28: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:28:1: W191 indentation contains tabs
./Arrange/arrange.py:29:1: W191 indentation contains tabs
./Arrange/arrange.py:29:7: W291 trailing whitespace
./Arrange/arrange.py:30:1: W191 indentation contains tabs
./Arrange/arrange.py:30:23: W291 trailing whitespace
./Arrange/arrange.py:32:37: W291 trailing whitespace
./Arrange/arrange.py:33:26: W291 trailing whitespace
./Arrange/arrange.py:34:35: W291 trailing whitespace
./Arrange/arrange.py:35:41: W291 trailing whitespace
./Arrange/arrange.py:37:36: W291 trailing whitespace
./Arrange/arrange.py:38:1: W191 indentation contains tabs
./Arrange/arrange.py:38:24: W291 trailing whitespace
./Arrange/arrange.py:39:1: W191 indentation contains tabs
./Arrange/arrange.py:39:24: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:39:26: W605 invalid escape sequence '\ '
./Arrange/arrange.py:39:29: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:39:39: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:39:41: W605 invalid escape sequence '\ '
./Arrange/arrange.py:39:44: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:39:52: W291 trailing whitespace
./Arrange/arrange.py:40:1: W191 indentation contains tabs
./Arrange/arrange.py:41:1: W191 indentation contains tabs
./Arrange/arrange.py:41:8: W291 trailing whitespace
./Arrange/arrange.py:42:1: W191 indentation contains tabs
./Arrange/arrange.py:42:19: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:42:21: W605 invalid escape sequence '\ '
./Arrange/arrange.py:42:24: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:42:35: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:42:37: W605 invalid escape sequence '\ '
./Arrange/arrange.py:42:40: E226 missing whitespace around arithmetic operator
./Arrange/arrange.py:42:51: W291 trailing whitespace
./Arrange/arrange.py:43:1: W191 indentation contains tabs
./Arrange/arrange.py:43:26: W291 trailing whitespace
./Arrange/arrange.py:44:1: W191 indentation contains tabs
./Arrange/arrange.py:44:8: W291 trailing whitespace
./Arrange/arrange.py:45:1: W191 indentation contains tabs
./Arrange/arrange.py:45:17: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:4:1: E302 expected 2 blank lines, found 1
./Currency_Convert/currencyconverter.py:4:26: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:5:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:5:44: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:6:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:6:12: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:7:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:7:2: E301 expected 1 blank line, found 0
./Currency_Convert/currencyconverter.py:7:26: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:8:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:8:34: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:10:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:10:49: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:11:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:11:29: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:13:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:13:56: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:14:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:14:39: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:15:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:15:56: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:16:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:16:26: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:17:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:17:30: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:18:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:18:47: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:20:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:20:47: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:21:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:21:54: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:22:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:22:84: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:24:14: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:25:1: E305 expected 2 blank lines after class or function definition, found 1
./Currency_Convert/currencyconverter.py:25:27: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:27:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:27:54: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:28:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:28:83: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:29:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:29:29: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:30:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:30:40: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:31:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:31:36: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:32:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:32:33: W291 trailing whitespace
./Currency_Convert/currencyconverter.py:34:1: W191 indentation contains tabs
./Currency_Convert/currencyconverter.py:34:45: W291 trailing whitespace
```
you can find it by clicking on detail, 
Install flake8 locally on your pc. there is also a vscode extension for too. try that

**Comment by codeperfectplus** [comment]
Please remove pictures and extra file(arrange.py and it's readme).
we need only
- readme
- requirements.txt
- script

**Comment by codeperfectplus** [comment]
re fork the repo and create a new PR.

**Pull request closed without merging**
