### PR TITLE
Created image to pencil sketch script

### LINKED ISSUE #112: convert image to pencil sketch
## Script Title -

**what will change** - This script will convert given image to pencil sketch using openCV

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by Neel2904**
Solved #112 
Used flake linting and added all required files.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
whitespace error

**Comment by Neel2904** [comment]
@codePerfectPlus  Done with that!!

**Comment by Neel2904** [comment]
@codePerfectPlus 
Can you please label this PR with hacktoberfest-accepted. because new guidelines are changed now.

**Comment by codeperfectplus** [comment]
there is no need for any label for hacktober, Hacktober label is only to encourage people for participating.

**Comment by Neel2904** [comment]
@codePerfectPlus 
checkout this link - https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Pull request merged**
