### PR TITLE
Create voice input output.py

### LINKED ISSUE #294: Voice input and output
## Script Title - Voice assistant interface

**what will change** -
* Take input in speech and convert into textfile
* Take text file as input and return voice output

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by itsjatin135s**
# Pull Request Template

**script name** - voice input output.py

hey buddy i had created "voice input output.py" file please review the code and add if you liked it .

Thank You

### CODE REVIEW

**Comment by codeperfectplus** [comment]
Hey, There is no Issue no. Please use the template for making the Pull request. It helps us to reduce spam and duplicate PR.
Please mention the issue no and correct the linting.

**Comment by itsjatin135s** [comment]
Hello @codePerfectPlus I am new to git hub so can you please suggest me about linting.
Issue no #317
Thank You

**Comment by codeperfectplus** [comment]
Code linting is used to find the possible error in the code and make code clean and readable.
Please check [flake8 documentation](https://flake8.pycqa.org/en/latest/) for more details.

**Comment by codeperfectplus** [comment]
No response to solve the flake8 error. PR will be close in 2 days

**Comment by itsjatin135s** [comment]
hey buddy I had used the code linting and now I think its fine please review.
Thank You

**Review by codeperfectplus — CHANGES_REQUESTED** [review]
alright, your script is now success on lint But there are some missing files.
- requirements.txt 
- A README for your script.

**Comment by itsjatin135s** [comment]
Hello I had created README.md and requirements.txt file please review and suggest if any change requires.
Thank You

**Review by codeperfectplus — APPROVED** [review]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
Happy Coding

**Pull request merged**
