### PR TITLE
Add script to send messages using Telegram 

### PR DESCRIPTION
**Pull request by javim-h**
Fix issue #14 . Send telegram messages from terminal.

### CODE REVIEW

**Comment by javim-h** [comment]
I deleted requirements file because cause conflicts with tests

**Comment by codeperfectplus** [comment]
you deleted the wrong file(python).

**Comment by javim-h** [comment]
Fixing issues with tests.

**Comment by javim-h** [comment]
> you deleted the wrong file(python).

Yep, fixed but test still fail

**Comment by codeperfectplus** [comment]
Click on details for error.
./send_telegram_message/send_telegram_message.py:10:1: E265 block comment should start with '# '
./send_telegram_message/send_telegram_message.py:18:9: W291 trailing whitespace
./send_telegram_message/send_telegram_message.py:18:9: E999 SyntaxError: invalid syntax

**Comment by javim-h** [comment]
> Click on details for error.
> ./send_telegram_message/send_telegram_message.py:10:1: E265 block comment should start with '# '
> ./send_telegram_message/send_telegram_message.py:18:9: W291 trailing whitespace
> ./send_telegram_message/send_telegram_message.py:18:9: E999 SyntaxError: invalid syntax

Yes i solved syntax error ( assigning a dumb value to it as credentials) I'm checking the other error, I thinks is a style error.

**Comment by javim-h** [comment]
Yes, lint give a error if I write a comment without space or import unused modules.

**Comment by codeperfectplus** [comment]
Thanks for making your contribution.

**Pull request merged**
