### PR TITLE
add Screenshot script

### PR DESCRIPTION
**Pull request by cozyxss**
Take a screenshot using Tkinter and PyAutoGui library. :camera: :sparkler:

### CODE REVIEW

**Comment by cozyxss** [comment]
I am new to open source projects and I didn't a lot of PR. 
That's why I have trouble using a lint. Sorry again so much fixed commit 😅

**Comment by codeperfectplus** [comment]
you can install flake8 extension in Vscode and atom.

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions

**Comment by cozyxss** [comment]
> you can install flake8 extension in Vscode and atom.

thank you for your advice 😄

**Pull request merged**
