### PR TITLE
Tear drops discord bot

### LINKED ISSUE #254: Discord Bot with economy and level-up system
## Script Title -
Tear_Drops
{a discord entertainment bot that has economy, levelup, wolfram query, etc...}
I would love to make this : )
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by Vyvy-vi**
# Pull Request Template

**script name** - TearDrops DISCORD_BOT

**What have you Changed**
I've added by bot project that I started a week ago..
It uses MongoDB as a database(It used TinyDB before that but that was unstable)
NOTE- I will continue this say after a week or two when I have time and add more functionality.
But, for now it functions satisfactorily.
The code has been linted. Though visual-indents were not addressed as they make the code look cleaner.
(I can make them one-line lists, if you guys tell me to)
I've tried to give documented code (but one shall need to read discord documentation to fully understand)

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

Join Us on Discord:- https://discord.gg/JfbK3bS

## acknowledgement
- [x] I have tested the script and distributing it under MIT license.

Star this repo!
: )

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
um... all the lint checks that failed are for long lines and continuations.
(does this have to be fixed too, since the embed etc. cause this)

**Comment by Vyvy-vi** [comment]
I'm sorry for the lint errors... I'm a bit inexperienced at linting my code

**Comment by Vyvy-vi** [comment]
It will be really helpful if this can maybe be merged
(I want to make a 12 PR record)

**Comment by Vyvy-vi** [comment]
Can this be added, I wanna make a PR record of 40

**Review by codeperfectplus — APPROVED** [review]

**Comment by codeperfectplus** [comment]
Thanks for making your Contributions.

**Pull request merged**
