### PR TITLE
Updated PR 304: Scrape_Wikipedia

### LINKED ISSUE #300: Scrape Wikipedia using speech recognition
## Script Title - Scrape Wikipedia using speech recognition

**what will change** -
-> Take input in speech and scrape Wikipedia using it
-> Output the result through speech as well

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by AnshikaY**
# Pull Request Template

**script name** - Scrape_Wikipedia_using_speech_recognition.py

**What have you Changed**
1)Added code to ->
-Take input in speech and scrape Wikipedia using it
-Output the result through speech as well
2)Added README.md file
3)Added requirements.txt file

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

Join Us on Discord:- https://discord.gg/JfbK3bS

## acknowledgement
- [x] I have tested the script and distributing it under MIT license.

### CODE REVIEW

**Comment by AnshikaY** [comment]
Working on flake8 error

**Comment by codeperfectplus** [comment]
congratulation

**Comment by codeperfectplus** [comment]
final step: create a folder scrap-Wikipedia-using-speech-recognition and move your script in that folder. so it will be easy to find the scripts when they will be in the folder.
Thanks

**Comment by codeperfectplus** [comment]
Alright, Everything looks to fix. 
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
Happy Coding

**Comment by AnshikaY** [comment]
> ## Alright, Everything looks to fix.
> Thanks for contributing to the repository. Looking more contribution in future.
> ## Join Py-Contributors Community
> [Discord](https://discord.gg/FXyh2S3) • [Telegram](https://t.me/pycontributors) • [website](https://py-contributors.github.io/)
> Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
> Happy Coding

Thanks for the patience! 
Regards.

**Pull request merged**
