### PR TITLE
MPU6050 Accelerometer Sensor Connector

### LINKED ISSUE #166: MPU6050 Accelerometer Sensor Connector PR: #165
## MPU6050 Accelerometer Sensor Connector -

**This script retrieves data from Accelerometer & Gyroscope and stored in the database. The code implements data storage in the MySQL database.** -

Update: Script has been created and a pull request is created here: #165

Happy Coding,

### PR DESCRIPTION
**Pull request by sigdelsanjog**

### CODE REVIEW

**Comment by codeperfectplus** [comment]
please create an issue describing your script.create folder name in small letters

**Comment by sigdelsanjog** [comment]
@codePerfectPlus  Issue created: #166 
Please review

**Comment by codeperfectplus** [comment]
@sigdelsanjog change folder name to lower case.

**Comment by sigdelsanjog** [comment]
@codePerfectPlus Issue has been linked with the PR and the folder name has been updated.

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions

**Pull request merged**
