### PR TITLE
Added YTS TOP MOVIES scripts

### LINKED ISSUE #358: YTS Top Movies
## YTS Top Movies

A new script that scraps data from [YTS](https://yts.mx) and shows:

- Most Popular Movies
- Latest Uploads
- Upcoming movies

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by chemsedd**
**YTS TOP MOVIES** -

A new script that scraps data from [YTS](https://yts.mx/) and shows:

- Most Popular Movies
- Latest Uploads
- Upcoming movies

### Self Check(Tick After Making pull Request)

- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

## acknowledgement
- [x] I have tested the script and distributing it under MIT license.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
hey @chemsedd,
Thanks for making the Pull request. we are using the flake8 standard to find the possible bugs and clean code. please can you check your script for the possible linting errors? you can check [Flake8](https://flake8.pycqa.org) documentation for help.

**Comment by chemsedd** [comment]
Sure will do, thanks for pointing out.

**Comment by chemsedd** [comment]
Flake8 errors fixed.

**Comment by codeperfectplus** [comment]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
Happy Coding

**Pull request merged**
