### PR TITLE
Added System info quick script

### PR DESCRIPTION
**Pull request by propenster**
Hi Guys! I came across this project and would like to contribute... here is a simple System info dumper in python... Environment: Python 3.8.5
Thank you.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
Thanks for making your contribution

**Comment by propenster** [comment]
You're welcome.... Is there a particular kind of scripts that are allowed or permissible? or it's just anything pythonic?

**Comment by codeperfectplus** [comment]
we are creating scripts to ease life tasks.

example
- Convert Html to PDF 
- Email sending Script
- Github Action Script

**Comment by propenster** [comment]
Hi Deepak,
Could you assign some issue to me please?
Thank you.
Regards,
Faith

**Comment by codeperfectplus** [comment]
New issues are coming out soon, If you have the idea for a new script then you can create an issue for that.

Make an issue and be assigned before making PR.

Happy coding,

**Comment by propenster** [comment]
OK. Thanks.

**Pull request merged**
