### PR TITLE
Added project-Extract mp3 from mp4

### LINKED ISSUE #94: Extract mp3 from mp4
## Script Title -Extracting mp3 from mp4 using Python

**what will change** -You can extract audio(mp3) from a video(mp4) file using Python in 5 lines of code. Your need to have the source-code in the same location of the video file, the program will generate a new mp3 file in that location

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by Shanu1515**
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [ ] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added README.md with my script

### CODE REVIEW

**Comment by codeperfectplus** [comment]
lint your code proper with flake8..

**Comment by TechTarun** [comment]
I want to improve this code, please assign me this

**Comment by codeperfectplus** [comment]
@TechTarun Code is not merged yet. once code will merge you can create an issue for improving code functionality. Assigning a task at the same will create conflict in the master branch.

**Comment by codeperfectplus** [comment]
@Shanu1515 Please lint your code proper with flake8.

**Comment by codeperfectplus** [comment]
Code Quality does not meet up to the requirement. please go through the documentation.

docs:- https://py-contributors.github.io/awesomeScripts/

**Pull request closed without merging**
