### PR TITLE
Scrape Wikipedia using speech recognition.py

### LINKED ISSUE #300: Scrape Wikipedia using speech recognition
## Script Title - Scrape Wikipedia using speech recognition

**what will change** -
-> Take input in speech and scrape Wikipedia using it
-> Output the result through speech as well

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server  - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by AnshikaY**
Using this script we can instruct to search on Wikipedia and get the result also in speech format.

# Pull Request Template

**script name** - Scrape Wikipedia using speech recognition

**What have you Changed**
-> Take input in speech and scrape Wikipedia using it
-> Output the result through speech as well

what you changed in the codebase.write here

### Issue no.(must) - #300 
[README.md.txt](https://github.com/Py-Contributors/awesomeScripts/files/5399803/README.md.txt)
[requirements.txt](https://github.com/Py-Contributors/awesomeScripts/files/5399804/requirements.txt)
[Scrape Wikipedia using speech recognition.txt](https://github.com/Py-Contributors/awesomeScripts/files/5399805/Scrape.Wikipedia.using.speech.recognition.txt)

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

Join Us on Discord:- https://discord.gg/JfbK3bS

## acknowledgement
- [x] I have tested the script and distributing it under MIT license.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
Please check the below issues.

- File Should be in seprate folder with README.md and requirements.txt
- Extension of the file is missing.

**Comment by AnshikaY** [comment]
@codePerfectPlus 
Hi, I am a beginner github user. Can you please elaborate what is to be done to rectify the issue - 
"File Should be in separate folder with README.md and requirements.txt"
Sorry for the mess.
Regards

**Comment by codeperfectplus** [comment]
Create a folder and add your Script, requirement.txt and Readme there. 
check the Main [README](https://github.com/Py-Contributors/awesomeScripts/blob/master/README.md) and [Contributing.md](https://github.com/Py-Contributors/awesomeScripts/blob/master/CONTRIBUTING.md) for more details.

**Comment by codeperfectplus** [comment]
No response to solve the flake8 error. PR will be close in 2 days

**Comment by AnshikaY** [comment]
@codePerfectPlus I figured the process and was about to correctly make it happen. This PR got closed even before the allotted time of 2 days ran out. Please consider re-opening this PR. Thanks anyways.

**Pull request closed without merging**
