### PR TITLE
New Code Added ( A Simple Space Shooter Game made using Pygame )

### LINKED ISSUE #549: Adding a simple space shooter game.
Hello ,
I want to contribute a simple space shooter game created using pygame library.

Programming Language:
Python

### PR DESCRIPTION
**Pull request by R0Y4L23**
Added a new space shooter game created using Pygame Library in Python.
The controls and installation process is simple and is provided inside the README.md within the folder.
Please merge. ( Issue #549 )

### CODE REVIEW

**Comment by codeperfectplus** [comment]
@R0Y4L23 You are using the Pygame module and adding the turtle library in requirements.txt. Please add the correct module in the correct Folder.

**Comment by R0Y4L23** [comment]
> @R0Y4L23 You are using the Pygame module and adding the turtle library in requirements.txt. Please add the correct module in the correct Folder.

Please can you check? My requirements.txt is there in my folder. The problem seems to be with some other folder which has requirements.txt. The gui_games is not my project. It is an existing project. 

Edit : Also it only contained one requiremnt i.e., turtle from the first. So merging wont cause an issue.

**Comment by codeperfectplus** [comment]
> > @R0Y4L23 You are using the Pygame module and adding the turtle library in requirements.txt. Please add the correct module in the correct Folder.
> 
> Please can you check? My requirements.txt is there in my folder. The problem seems to be with some other folder which has requirements.txt. The gui_games is not my project. It is an existing project.
> 
> Edit : Also it only contained one requiremnt i.e., turtle from the first. So merging wont cause an issue.

Thanks for adding requirements.txt, Please try to `git pull origin` before making changes to avoid any merge conflict.

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions.

you can join us on telegram for more updates about Hacktoberfest.
Hacktoberfest Channel:- t.me/hacktober2022

Happy hacktoberfest

**Comment by R0Y4L23** [comment]
Welcome.
Also Thank you for merging.
I will surely join the telegram channel.

**Pull request merged**
