### PR TITLE
Automated movies and TV series search using python scripts

### PR DESCRIPTION
**Pull request by harsh7x18**
IT IS A MINI-IMDB PROJECT THAT PROVIDES INFORMATION ABOUT ANY MOVIE OR TV SERIES WHEN SEARCHED.
This project is coded in python language and uses basics of python data structure - lists, OOPS and some basics of database.
Do remember to read the documentation at the top of the source code for smooth learning.

### CODE REVIEW

**Comment by codeperfectplus** [comment]
Please create an issue and lint your code with flake8

**Comment by codeperfectplus** [comment]
provide README.md and requirements or pipenv as well. Put your file in the folder. 
**mini-imbd** or relevant name

**Comment by codeperfectplus** [comment]
your file should be in your folder only. remove a copy of your file from the main dir.
requirements.txt format is wrong. go through documentation once. 
https://note.nkmk.me/en/python-pip-install-requirements/

**Comment by harsh7x18** [comment]
Made a new pull request using branch name ten. Kindly review!

**Pull request closed without merging**
