### PR TITLE
website blocker using python

### PR DESCRIPTION
**Pull request by Mr-Mishraji**
# Pull Request Template

**script name** - website blocker

**What have you Changed**

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [ ] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

Join Us on Discord:- https://discord.gg/JfbK3bS

## acknowledgement
- [x] I have tested the script and distributing it under MIT license.

### CODE REVIEW

**Comment by Mr-Mishraji** [comment]
why it is getting failed remark

**Comment by codeperfectplus** [comment]
correct your code according to flake8 standards. Check [flake8 documentation](https://flake8.pycqa.org/)
you can check error by clicking on details or you can download flake8 via pip locally.
.

**Comment by codeperfectplus** [comment]
Alright, your codes passed the flake8 standards. But still, you have to change some basic things.

- [ ] your script should be in the separate folder not in the root directory.
- [ ] there should be a README for the script introduction and usages.

You can check all the steps [here](https://github.com/py-contributors/awesomescripts#here-are-the-steps-to-make-contribute-)

thanks for having patience

**Comment by codeperfectplus** [comment]
inactive PR. It will be close in 2 days if there will be no response.
@Mr-Mishraji

**Pull request closed without merging**
